### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by thalesmaoa** [obeone/docker-nfs-server#10]
Hi @obeone, thanks for creating this fork.

After deploying, I'm getting connection refused. Any thoughts about it?

```
services:
  nfs-server:
    image: ghcr.io/obeone/nfs-server
    container_name: nfs-server
    cap_add:
      - SYS_MODULE
      - SYS_ADMIN
    volumes:
      - /home/thales/External:/shared
      - ./config/exports:/etc/exports:ro # location of kernel headers
      - /lib/modules:/lib/modules:ro
    ports:
      - 2049:2049
    restart: unless-stopped
```

I'm ruining in a RPi 3 B
